name: E2E Tests

on:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t react-app:ci .

      - name: Run container
        run: docker run -d --rm -p 3000:3000 --name react-app react-app:ci
      
      - name: Wait for app to start
        run: |
          echo "Waiting for app to be ready..."
          timeout 60 sh -c 'until curl -f http://localhost:3000 > /dev/null 2>&1; do sleep 2; done'
          echo "App is ready!"

      - name: Clone E2E test repo
        run: git clone https://github.com/ayrton-sf/playwright-pytest-todomvc.git

      - name: Install Playwright dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r playwright-pytest-todomvc/requirements.txt
          playwright install --with-deps chromium

      - name: Run Playwright tests
        run: |
          cd playwright-pytest-todomvc
          pytest -v

      - name: Stop container
        if: always()
        run: docker stop react-app || true
